const { spawn, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const MEDIAMTX_DIR = '/opt/mediamtx';
const MEDIAMTX_BIN = path.join(MEDIAMTX_DIR, 'mediamtx');
const MEDIAMTX_CONF = path.join(MEDIAMTX_DIR, 'mediamtx.yml');

class CameraManager {
  constructor(config, mqtt) {
    this.config = config;
    this.mqtt = mqtt;
    this.process = null;
    this.streaming = false;
    this.cameraType = null;   // 'usb' | 'pi' | null
    this.devicePath = null;   // e.g. /dev/video0
    this.streamPorts = {
      rtsp: 8554,
      webrtc: 8889,
      hls: 8888,
    };
  }

  /**
   * Detect available cameras and determine type.
   * USB cameras show up as /dev/video* via v4l2.
   * Pi camera shows up via libcamera.
   */
  detect() {
    // Check for USB camera via v4l2
    const usbDevice = this._detectUsb();
    if (usbDevice) {
      this.cameraType = 'usb';
      this.devicePath = usbDevice;
      console.log(`[CAMERA] USB camera detected at ${usbDevice}`);
      return { type: 'usb', device: usbDevice };
    }

    // Check for Pi camera via libcamera
    if (this._detectPiCamera()) {
      this.cameraType = 'pi';
      this.devicePath = null; // libcamera doesn't use /dev/video*
      console.log('[CAMERA] Pi camera detected via libcamera');
      return { type: 'pi', device: 'libcamera' };
    }

    console.log('[CAMERA] No camera detected');
    return null;
  }

  _detectUsb() {
    try {
      const output = execSync('v4l2-ctl --list-devices 2>/dev/null', {
        encoding: 'utf8',
        timeout: 5000,
      });
      // Parse output: each device block starts with a non-indented header line,
      // followed by indented /dev/* paths. We want the first /dev/video* under
      // a USB camera header (contains "usb") and skip platform devices (pispbe, rpi-).
      const lines = output.split('\n');
      let inUsbBlock = false;
      for (const line of lines) {
        const trimmed = line.trim();
        // Header lines are not indented (no leading whitespace)
        if (line.length > 0 && line[0] !== '\t' && line[0] !== ' ') {
          // Check if this is a USB device (not a platform ISP/decoder)
          const lower = trimmed.toLowerCase();
          inUsbBlock = lower.includes('usb') && !lower.includes('pispbe') && !lower.includes('rpi-');
        } else if (inUsbBlock && trimmed.startsWith('/dev/video')) {
          // First /dev/video* under a USB block is the capture device
          return trimmed;
        }
      }
    } catch {}
    // Fallback: check if /dev/video0 exists (common for USB cameras)
    if (fs.existsSync('/dev/video0')) return '/dev/video0';
    return null;
  }

  _detectPiCamera() {
    try {
      execSync('libcamera-hello --list-cameras 2>&1', { timeout: 5000 });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get the local IP address for constructing stream URLs.
   */
  _getLocalIp() {
    const nets = os.networkInterfaces();
    for (const iface of Object.values(nets)) {
      for (const entry of iface) {
        if (entry.family === 'IPv4' && !entry.internal) return entry.address;
      }
    }
    return '127.0.0.1';
  }

  /**
   * Build MediaMTX config based on detected camera type.
   */
  _writeMediaMtxConfig() {
    let sourceConfig;

    if (this.cameraType === 'usb') {
      sourceConfig = `    source: v4l2://${this.devicePath}`;
    } else if (this.cameraType === 'pi') {
      // MediaMTX has native rpiCamera support
      sourceConfig = `    source: rpiCamera`;
    } else {
      throw new Error('No camera detected — cannot configure stream');
    }

    const config = `# Auto-generated by intrlock-bridge-agent
# Do not edit — regenerated on each start

logLevel: warn

api: yes
apiAddress: 127.0.0.1:9997

rtsp: yes
rtspAddress: :${this.streamPorts.rtsp}

webrtc: yes
webrtcAddress: :${this.streamPorts.webrtc}

hls: yes
hlsAddress: :${this.streamPorts.hls}

paths:
  cam:
${sourceConfig}
`;

    fs.mkdirSync(path.dirname(MEDIAMTX_CONF), { recursive: true });
    fs.writeFileSync(MEDIAMTX_CONF, config);
    console.log('[CAMERA] MediaMTX config written');
  }

  /**
   * Start the video stream by spawning MediaMTX.
   */
  async start() {
    if (this.streaming) {
      console.log('[CAMERA] Already streaming');
      return this.getStreamUrls();
    }

    // Detect camera if not already done
    if (!this.cameraType) {
      const detected = this.detect();
      if (!detected) {
        console.log('[CAMERA] No camera available — stream not started');
        return null;
      }
    }

    // Check MediaMTX binary exists
    if (!fs.existsSync(MEDIAMTX_BIN)) {
      console.error('[CAMERA] MediaMTX not installed at ' + MEDIAMTX_BIN);
      console.error('[CAMERA] Run: sudo /opt/intrlock-bridge/scripts/install-mediamtx.sh');
      return null;
    }

    // Write config
    this._writeMediaMtxConfig();

    // Kill any existing MediaMTX process
    this._killExisting();

    return new Promise((resolve) => {
      console.log('[CAMERA] Starting MediaMTX...');
      this.process = spawn(MEDIAMTX_BIN, [MEDIAMTX_CONF], {
        stdio: ['ignore', 'pipe', 'pipe'],
        detached: false,
      });

      let started = false;

      this.process.stdout.on('data', (data) => {
        const line = data.toString().trim();
        if (line) console.log(`[MEDIAMTX] ${line}`);
        if (!started && (line.includes('listener opened') || line.includes('is ready'))) {
          started = true;
          this.streaming = true;
          const urls = this.getStreamUrls();
          console.log('[CAMERA] Stream started');
          console.log(`[CAMERA]   RTSP:   ${urls.rtsp}`);
          console.log(`[CAMERA]   WebRTC: ${urls.webrtc}`);
          console.log(`[CAMERA]   HLS:    ${urls.hls}`);
          this._publishEvent('stream_started', urls);
          resolve(urls);
        }
      });

      this.process.stderr.on('data', (data) => {
        const line = data.toString().trim();
        if (line) console.error(`[MEDIAMTX-ERR] ${line}`);
      });

      this.process.on('exit', (code) => {
        console.log(`[CAMERA] MediaMTX exited with code ${code}`);
        this.streaming = false;
        this.process = null;
        this._publishEvent('stream_stopped', { exit_code: code });
      });

      this.process.on('error', (err) => {
        console.error('[CAMERA] Failed to start MediaMTX:', err.message);
        this.streaming = false;
        this.process = null;
        resolve(null);
      });

      // Timeout — if MediaMTX doesn't log readiness in 10s, assume it started
      setTimeout(() => {
        if (!started && this.process && !this.process.killed) {
          started = true;
          this.streaming = true;
          resolve(this.getStreamUrls());
        }
      }, 10000);
    });
  }

  /**
   * Stop the video stream.
   */
  stop() {
    if (this.process) {
      console.log('[CAMERA] Stopping MediaMTX...');
      this.process.kill('SIGTERM');
      // Force kill after 5s
      setTimeout(() => {
        if (this.process) {
          this.process.kill('SIGKILL');
          this.process = null;
        }
      }, 5000);
    }
    this.streaming = false;
    this._killExisting();
    this._publishEvent('stream_stopped', {});
  }

  _killExisting() {
    try {
      execSync('pkill -f mediamtx 2>/dev/null', { stdio: 'ignore', timeout: 3000 });
    } catch {}
  }

  /**
   * Get current stream URLs.
   */
  getStreamUrls() {
    const ip = this._getLocalIp();
    return {
      rtsp: `rtsp://${ip}:${this.streamPorts.rtsp}/cam`,
      webrtc: `http://${ip}:${this.streamPorts.webrtc}/cam`,
      hls: `http://${ip}:${this.streamPorts.hls}/cam`,
      ip,
    };
  }

  /**
   * Get camera status for health reports.
   */
  getStatus() {
    return {
      camera_detected: !!this.cameraType,
      camera_type: this.cameraType,
      camera_device: this.devicePath,
      streaming: this.streaming,
      stream_urls: this.streaming ? this.getStreamUrls() : null,
    };
  }

  /**
   * Publish a camera event via MQTT.
   */
  _publishEvent(eventType, data) {
    if (this.mqtt) {
      this.mqtt.publish('event', {
        event_type: eventType,
        ...data,
        timestamp: Date.now(),
      });
    }
  }

  /**
   * Cleanup on shutdown.
   */
  cleanup() {
    this.stop();
  }
}

module.exports = { CameraManager };
