const fs = require('fs');
const path = require('path');

const CONFIG_DIR = process.env.BRIDGE_DIR || '/opt/intrlock-bridge';
const CAMERAS_PATH = path.join(CONFIG_DIR, 'config', 'cameras.json');
const MEDIAMTX_CONF = '/opt/mediamtx/mediamtx.yml';

const DEFAULT_CAMERAS_CONFIG = {
  cameras: [],
  recording_settings: {
    segment_duration: 300,
    retention_days: 30,
    max_disk_percent: 90,
    usb_mount_path: '/mnt/usb',
  },
};

let cameraData = null;

function load() {
  try {
    if (fs.existsSync(CAMERAS_PATH)) {
      const raw = fs.readFileSync(CAMERAS_PATH, 'utf8');
      cameraData = { ...DEFAULT_CAMERAS_CONFIG, ...JSON.parse(raw) };
      return cameraData;
    }
  } catch (e) {
    console.error('[CAMERA-CONFIG] Failed to load:', e.message);
  }

  // First run — generate defaults
  cameraData = { ...DEFAULT_CAMERAS_CONFIG };
  save(cameraData);
  return cameraData;
}

function save(data) {
  try {
    fs.mkdirSync(path.dirname(CAMERAS_PATH), { recursive: true });
    fs.writeFileSync(CAMERAS_PATH, JSON.stringify(data, null, 2));
    cameraData = data;
  } catch (e) {
    console.error('[CAMERA-CONFIG] Failed to save:', e.message);
  }
}

function addCamera(camera) {
  if (!cameraData) load();

  const newCamera = {
    id: camera.id || `cam${Date.now().toString(36)}`,
    name: camera.name || '',
    ip: camera.ip || '',
    rtsp_url: camera.rtsp_url || '',
    sub_stream_url: camera.sub_stream_url || '',
    username: camera.username || '',
    password: camera.password || '',
    manufacturer: camera.manufacturer || '',
    model: camera.model || '',
    recording: camera.recording !== undefined ? camera.recording : false,
    enabled: camera.enabled !== undefined ? camera.enabled : true,
  };

  cameraData.cameras.push(newCamera);
  save(cameraData);
  regenerateMediaMtx();
  return newCamera;
}

function updateCamera(id, updates) {
  if (!cameraData) load();

  const index = cameraData.cameras.findIndex((c) => c.id === id);
  if (index === -1) return null;

  cameraData.cameras[index] = { ...cameraData.cameras[index], ...updates, id };
  save(cameraData);
  regenerateMediaMtx();
  return cameraData.cameras[index];
}

function removeCamera(id) {
  if (!cameraData) load();

  const index = cameraData.cameras.findIndex((c) => c.id === id);
  if (index === -1) return false;

  cameraData.cameras.splice(index, 1);
  save(cameraData);
  regenerateMediaMtx();
  return true;
}

function getCamera(id) {
  if (!cameraData) load();

  return cameraData.cameras.find((c) => c.id === id) || null;
}

function listCameras() {
  if (!cameraData) load();

  return [...cameraData.cameras];
}

function getRecordingSettings() {
  if (!cameraData) load();

  return { ...cameraData.recording_settings };
}

function updateRecordingSettings(settings) {
  if (!cameraData) load();

  cameraData.recording_settings = { ...cameraData.recording_settings, ...settings };
  save(cameraData);
  return { ...cameraData.recording_settings };
}

function regenerateMediaMtx(data) {
  if (!cameraData) load();

  const cameras = data?.cameras || cameraData.cameras;
  const enabledCams = cameras.filter(c => c.enabled && (c.rtsp_url || c.ffmpeg_source || c.rpi_camera));

  let paths = '';
  for (const cam of enabledCams) {
    paths += `  ${cam.id}:\n`;
    if (cam.rpi_camera) {
      // Pi Camera Module (CSI) — use native rpiCamera source
      paths += `    source: rpiCamera\n`;
    } else if (cam.ffmpeg_source && cam.rtsp_url) {
      // Local device with separate stream URL (e.g., rpicam-vid TCP output)
      paths += `    source: ${cam.rtsp_url}\n`;
      paths += `    runOnInit: ${cam.ffmpeg_source}\n`;
      paths += `    runOnInitRestart: yes\n`;
    } else if (cam.ffmpeg_source) {
      // Local device pushing directly to MediaMTX (e.g., USB webcam)
      paths += `    runOnInit: ${cam.ffmpeg_source}\n`;
      paths += `    runOnInitRestart: yes\n`;
    } else {
      paths += `    source: ${cam.rtsp_url}\n`;
    }
  }

  const yml = `# Auto-generated by intrlock-bridge-agent dashboard
# Do not edit manually — regenerated when cameras change

logLevel: warn
api: yes
apiAddress: :9997

rtspAddress: :8554
webrtcAddress: :8889
hlsAddress: :8888

paths:
${paths || '  # No cameras configured\n'}`;

  try {
    fs.mkdirSync(path.dirname(MEDIAMTX_CONF), { recursive: true });
    fs.writeFileSync(MEDIAMTX_CONF, yml);
    console.log(`[CAMERA-CONFIG] MediaMTX config written with ${enabledCams.length} cameras`);
  } catch (e) {
    console.error('[CAMERA-CONFIG] Failed to write MediaMTX config:', e.message);
  }
}

module.exports = {
  load,
  save,
  addCamera,
  updateCamera,
  removeCamera,
  getCamera,
  listCameras,
  getRecordingSettings,
  updateRecordingSettings,
  regenerateMediaMtx,
  CAMERAS_PATH,
  MEDIAMTX_CONF,
};
