const { spawn, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const MEDIAMTX_DIR = '/opt/mediamtx';
const MEDIAMTX_BIN = path.join(MEDIAMTX_DIR, 'mediamtx');
const MEDIAMTX_CONF = path.join(MEDIAMTX_DIR, 'mediamtx.yml');

class CameraManager {
  constructor(config, mqtt) {
    this.config = config;
    this.mqtt = mqtt;
    this.process = null;
    this.ffmpegProcess = null;
    this.streaming = false;
    this.cameraType = null;   // 'usb' | 'pi' | 'ip' | null
    this.devicePath = null;   // /dev/video0, rtsp://..., etc.
    this.relayHost = config.relay_host || null;  // EC2 public IP for remote viewing
    this.streamPorts = {
      rtsp: 8554,
      webrtc: 8889,
      hls: 8888,
    };
    // IP cameras configured in config.json
    this.ipCameras = config.ip_cameras || [];
  }

  /**
   * Detect available cameras. Priority: USB > Pi Camera > IP cameras from config.
   */
  detect() {
    // Check for USB camera via v4l2
    const usbDevice = this._detectUsb();
    if (usbDevice) {
      this.cameraType = 'usb';
      this.devicePath = usbDevice;
      console.log(`[CAMERA] USB camera detected at ${usbDevice}`);
      return { type: 'usb', device: usbDevice };
    }

    // Check for Pi camera via libcamera
    if (this._detectPiCamera()) {
      this.cameraType = 'pi';
      this.devicePath = null;
      console.log('[CAMERA] Pi camera detected via libcamera');
      return { type: 'pi', device: 'libcamera' };
    }

    // Check for configured IP cameras
    if (this.ipCameras.length > 0) {
      const cam = this.ipCameras[0]; // Use first configured IP camera
      this.cameraType = 'ip';
      this.devicePath = cam.rtsp_url || cam.url;
      console.log(`[CAMERA] IP camera configured: ${cam.name || this.devicePath}`);
      return { type: 'ip', device: this.devicePath, name: cam.name };
    }

    console.log('[CAMERA] No camera detected');
    return null;
  }

  _detectUsb() {
    try {
      const output = execSync('v4l2-ctl --list-devices 2>/dev/null', {
        encoding: 'utf8',
        timeout: 5000,
      });
      const lines = output.split('\n');
      let inUsbBlock = false;
      for (const line of lines) {
        const trimmed = line.trim();
        if (line.length > 0 && line[0] !== '\t' && line[0] !== ' ') {
          const lower = trimmed.toLowerCase();
          inUsbBlock = lower.includes('usb') && !lower.includes('pispbe') && !lower.includes('rpi-');
        } else if (inUsbBlock && trimmed.startsWith('/dev/video')) {
          return trimmed;
        }
      }
    } catch {}
    if (fs.existsSync('/dev/video0')) return '/dev/video0';
    return null;
  }

  _detectPiCamera() {
    try {
      execSync('libcamera-hello --list-cameras 2>&1', { timeout: 5000 });
      return true;
    } catch {
      return false;
    }
  }

  _getLocalIp() {
    const nets = os.networkInterfaces();
    for (const iface of Object.values(nets)) {
      for (const entry of iface) {
        if (entry.family === 'IPv4' && !entry.internal) return entry.address;
      }
    }
    return '127.0.0.1';
  }

  /**
   * Build the FFmpeg source command based on camera type and relay config.
   * Target is either local MediaMTX or remote relay.
   */
  _buildFfmpegCmd(rtspTarget) {
    if (this.cameraType === 'usb') {
      return `ffmpeg -f v4l2 -input_format mjpeg -video_size 1280x720 -framerate 15 -i ${this.devicePath} -f alsa -i default -c:v libx264 -preset ultrafast -tune zerolatency -g 30 -c:a aac -b:a 64k -f rtsp ${rtspTarget}`;
    }
    if (this.cameraType === 'ip') {
      // Re-stream IP camera: pull RTSP, re-push to our MediaMTX/relay
      return `ffmpeg -rtsp_transport tcp -i ${this.devicePath} -c:v copy -c:a copy -f rtsp ${rtspTarget}`;
    }
    return null; // Pi camera uses native MediaMTX source
  }

  /**
   * Build MediaMTX config. For USB/IP cameras, uses FFmpeg publisher.
   * For Pi camera, uses native rpiCamera source.
   */
  _writeMediaMtxConfig() {
    let sourceConfig;

    if (this.cameraType === 'usb' || this.cameraType === 'ip') {
      const target = `rtsp://localhost:${this.streamPorts.rtsp}/cam`;
      const ffmpegCmd = this._buildFfmpegCmd(target);
      sourceConfig = `    source: publisher
    runOnInit: ${ffmpegCmd}
    runOnInitRestart: yes`;
    } else if (this.cameraType === 'pi') {
      sourceConfig = `    source: rpiCamera`;
    } else {
      throw new Error('No camera detected — cannot configure stream');
    }

    const config = `# Auto-generated by intrlock-bridge-agent
# Do not edit — regenerated on each start

logLevel: warn

api: yes
apiAddress: 127.0.0.1:9997

rtsp: yes
rtspAddress: :${this.streamPorts.rtsp}

webrtc: yes
webrtcAddress: :${this.streamPorts.webrtc}

hls: yes
hlsAddress: :${this.streamPorts.hls}

paths:
  cam:
${sourceConfig}
`;

    fs.mkdirSync(path.dirname(MEDIAMTX_CONF), { recursive: true });
    fs.writeFileSync(MEDIAMTX_CONF, config);
    console.log('[CAMERA] MediaMTX config written');
  }

  /**
   * Start the video stream. Spawns local MediaMTX and optionally
   * a second FFmpeg process to relay to the remote EC2 server.
   */
  async start() {
    if (this.streaming) {
      console.log('[CAMERA] Already streaming');
      return this.getStreamUrls();
    }

    if (!this.cameraType) {
      const detected = this.detect();
      if (!detected) {
        console.log('[CAMERA] No camera available — stream not started');
        return null;
      }
    }

    if (!fs.existsSync(MEDIAMTX_BIN)) {
      console.error('[CAMERA] MediaMTX not installed at ' + MEDIAMTX_BIN);
      console.error('[CAMERA] Run: sudo /opt/intrlock-bridge/scripts/install-mediamtx.sh');
      return null;
    }

    this._writeMediaMtxConfig();
    this._killExisting();

    return new Promise((resolve) => {
      console.log('[CAMERA] Starting MediaMTX...');
      this.process = spawn(MEDIAMTX_BIN, [MEDIAMTX_CONF], {
        stdio: ['ignore', 'pipe', 'pipe'],
        detached: false,
      });

      let started = false;

      this.process.stdout.on('data', (data) => {
        const line = data.toString().trim();
        if (line) console.log(`[MEDIAMTX] ${line}`);
        if (!started && (line.includes('listener opened') || line.includes('is ready'))) {
          started = true;
          this._onStreamReady(resolve);
        }
      });

      this.process.stderr.on('data', (data) => {
        const line = data.toString().trim();
        // Suppress FFmpeg progress spam — only log actual errors
        if (line && !line.startsWith('frame=') && !line.startsWith('size=')) {
          console.error(`[MEDIAMTX-ERR] ${line}`);
        }
      });

      this.process.on('exit', (code) => {
        console.log(`[CAMERA] MediaMTX exited with code ${code}`);
        this.streaming = false;
        this.process = null;
        this._stopRelay();
        this._publishEvent('stream_stopped', { exit_code: code });
      });

      this.process.on('error', (err) => {
        console.error('[CAMERA] Failed to start MediaMTX:', err.message);
        this.streaming = false;
        this.process = null;
        resolve(null);
      });

      // Timeout — if MediaMTX doesn't log readiness in 10s, assume it started
      setTimeout(() => {
        if (!started && this.process && !this.process.killed) {
          started = true;
          this._onStreamReady(resolve);
        }
      }, 10000);
    });
  }

  /**
   * Called when local MediaMTX is ready. Starts relay to EC2 if configured.
   */
  _onStreamReady(resolve) {
    this.streaming = true;
    const urls = this.getStreamUrls();
    console.log('[CAMERA] Stream started');
    console.log(`[CAMERA]   Local WebRTC: ${urls.local.webrtc}`);

    // Start relay to EC2 if relay_host is configured
    if (this.relayHost) {
      this._startRelay();
      console.log(`[CAMERA]   Remote WebRTC: ${urls.remote.webrtc}`);
    }

    this._publishEvent('stream_started', urls);
    resolve(urls);
  }

  /**
   * Push local RTSP stream to the remote EC2 relay via FFmpeg.
   */
  _startRelay() {
    if (!this.relayHost || this.ffmpegProcess) return;

    const localRtsp = `rtsp://127.0.0.1:${this.streamPorts.rtsp}/cam`;
    const remoteRtsp = `rtsp://${this.relayHost}:${this.streamPorts.rtsp}/cam`;

    console.log(`[RELAY] Pushing stream to ${this.relayHost}...`);

    this.ffmpegProcess = spawn('ffmpeg', [
      '-rtsp_transport', 'tcp',
      '-i', localRtsp,
      '-c:v', 'copy',
      '-c:a', 'copy',
      '-f', 'rtsp',
      remoteRtsp,
    ], { stdio: ['ignore', 'ignore', 'pipe'] });

    this.ffmpegProcess.stderr.on('data', (data) => {
      const line = data.toString().trim();
      // Only log errors, not progress
      if (line && !line.startsWith('frame=') && !line.startsWith('size=')) {
        console.error(`[RELAY-ERR] ${line}`);
      }
    });

    this.ffmpegProcess.on('exit', (code) => {
      console.log(`[RELAY] FFmpeg relay exited with code ${code}`);
      this.ffmpegProcess = null;
      // Auto-restart relay if still streaming
      if (this.streaming && this.relayHost) {
        console.log('[RELAY] Restarting in 5s...');
        setTimeout(() => this._startRelay(), 5000);
      }
    });
  }

  _stopRelay() {
    if (this.ffmpegProcess) {
      this.ffmpegProcess.kill('SIGTERM');
      setTimeout(() => {
        if (this.ffmpegProcess) {
          this.ffmpegProcess.kill('SIGKILL');
          this.ffmpegProcess = null;
        }
      }, 3000);
    }
  }

  stop() {
    if (this.process) {
      console.log('[CAMERA] Stopping MediaMTX...');
      this.process.kill('SIGTERM');
      setTimeout(() => {
        if (this.process) {
          this.process.kill('SIGKILL');
          this.process = null;
        }
      }, 5000);
    }
    this._stopRelay();
    this.streaming = false;
    this._killExisting();
    this._publishEvent('stream_stopped', {});
  }

  _killExisting() {
    try {
      execSync('pkill -f mediamtx 2>/dev/null', { stdio: 'ignore', timeout: 3000 });
    } catch {}
  }

  /**
   * Get stream URLs — both local and remote (if relay configured).
   */
  getStreamUrls() {
    const localIp = this._getLocalIp();
    const urls = {
      local: {
        rtsp: `rtsp://${localIp}:${this.streamPorts.rtsp}/cam`,
        webrtc: `http://${localIp}:${this.streamPorts.webrtc}/cam`,
        hls: `http://${localIp}:${this.streamPorts.hls}/cam`,
      },
      // Keep flat rtsp/webrtc/hls for backwards compat
      rtsp: `rtsp://${localIp}:${this.streamPorts.rtsp}/cam`,
      webrtc: `http://${localIp}:${this.streamPorts.webrtc}/cam`,
      hls: `http://${localIp}:${this.streamPorts.hls}/cam`,
      ip: localIp,
    };

    if (this.relayHost) {
      urls.remote = {
        rtsp: `rtsp://${this.relayHost}:${this.streamPorts.rtsp}/cam`,
        webrtc: `http://${this.relayHost}:${this.streamPorts.webrtc}/cam`,
        hls: `http://${this.relayHost}:${this.streamPorts.hls}/cam`,
      };
      // Default URLs point to remote when relay is configured
      urls.rtsp = urls.remote.rtsp;
      urls.webrtc = urls.remote.webrtc;
      urls.hls = urls.remote.hls;
    }

    return urls;
  }

  getStatus() {
    return {
      camera_detected: !!this.cameraType,
      camera_type: this.cameraType,
      camera_device: this.devicePath,
      streaming: this.streaming,
      relay_host: this.relayHost,
      relay_active: !!this.ffmpegProcess,
      ip_cameras: this.ipCameras,
      stream_urls: this.streaming ? this.getStreamUrls() : null,
    };
  }

  _publishEvent(eventType, data) {
    if (this.mqtt) {
      this.mqtt.publish('event', {
        event_type: eventType,
        ...data,
        timestamp: Date.now(),
      });
    }
  }

  cleanup() {
    this.stop();
  }
}

module.exports = { CameraManager };
